### ISSUE TITLE
Unable to connect Mongoose

### ISSUE THREAD

**Issue by Sandeepbhatt3287** [Sandeepbhatt3287/Minor_project#2]
[nodemon] starting `node index.js`
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'mongoose'
Require stack:
- D:\nodews\TODO_list\config\mongoose.js
- D:\nodews\TODO_list\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\nodews\TODO_list\config\mongoose.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\nodews\\TODO_list\\config\\mongoose.js',
    'D:\\nodews\\TODO_list\\index.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Sandeepbhatt3287** [comment]
First I have installed mongoose, using ths command:
npm install mongoose

After that I am facing same issue, then I tried this:

PS D:\nodews\TODO_list> **npm link mongoose**
D:\nodews\TODO_list\node_modules\mongoose -> C:\Users\sande\AppData\Roaming\npm\node_modules\mongoose
PS D:\nodews\TODO_list> nodemon index.js    
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
body-parser deprecated undefined extended: provide extended 
option index.js:14:17
(node:13988) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:13988) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
yeah!!! my express server is running on port : 8000
